### ISSUE TITLE
packaging request: burp package for Chocolatey (Ansible)

### ISSUE THREAD

**Issue by jirib** [grke/burp#697]
Hi,

as you refer to Ansible on the wiki, maybe it would be nice to have a package in Chocolatey so Windows boxes could have burp installed via Ansible's 'win_chocolatey' module.

```        
Manage packages using Chocolatey (http://chocolatey.org/).
If Chocolatey is missing from the system, the module will install it.
List of packages can be found at http://chocolatey.org/packages.
```

Example:

```
- name: Install burp
  win_chocolatey:
    name: burp
    state: present
```

I could write a wiki page about Ansible, Windows and burp, if needed.
