### ISSUE TITLE
[burp-2.2.10][debian] Possible problem incexc

### ISSUE THREAD

**Issue by jacky35** [grke/burp#762]
Hello,
So maybe I'm wrong.
But I have the impression that I can not apply the server-side parameters on the client.

Here is my configuration:

--------
/etc/burp/clientconfdir/poste999
--------
```
password = abcdefgh

# More configuration files can be read, using syntax like the following
# (without the leading '# ').

split_vss = 0
strip_vss = 1
exclude_regex =\/*Private*\/
exclude_ext = vdi
```

--------
burp -c /etc/burp/burp-server.conf -t -C poste999
--------

```
                        conffile: /etc/burp/burp-server.conf
                          syslog: 1
                          stdout: 0
                progress_counter: 0
                            user: burp
                           group: backup
                        protocol: 0
                       directory: /var/spool/burp
                timestamp_format: %Y-%m-%d %H:%M:%S %z
                   clientconfdir: /etc/burp/clientconfdir
                  client_lockdir:
                  directory_tree: 1
                  password_check: 1
                   manual_delete:
                 rblk_memory_max: 268435456
            monitor_browse_cache: 0
                         enabled: 1
                         include:
                         exclude:
                cross_filesystem:
                        nobackup:
                     include_ext:
                     exclude_ext: vdi
                   include_regex:
                   exclude_regex: \/*Private*\/
                      exclude_fs:
                      include_fs:
                    exclude_comp:
                    include_glob:
           cross_all_filesystems: 0
                  read_all_fifos: 0
                       read_fifo:
              read_all_blockdevs: 0
                   read_blockdev:
                   min_file_size: 0
                   max_file_size: 0
                       split_vss: 0
                       strip_vss: 1
                      vss_drives:
                             acl: 1
                           xattr: 1
                           atime: 0
       scan_problem_raises_error: 0
                       overwrite: 0
                           strip: 0
                           regex:
               server_script_pre:
           server_script_pre_arg:
        server_script_pre_notify: 0
              server_script_post:
          server_script_post_arg:
  server_script_post_run_on_fail: 0
       server_script_post_notify: 0
                   server_script:
               server_script_arg:
            server_script_notify: 0
              hardlinked_archive: 1
                            keep: 7
     working_dir_recovery_method: delete
                 fail_on_warning: 0
             max_resume_attempts: 0
                        librsync: 1
               librsync_max_size: 0
                     compression: 9
                    version_warn: 1
                path_length_warn: 1
                      hard_quota: 0
                      soft_quota: 0
                    timer_script:
                       timer_arg: 1s
                       timer_arg: Mon,Tue,Wed,Thu,Fri,00,01,02,03,04,05,16,17,18,19,20,21,22,23
                       timer_arg: Sat,Sun,00,01,02,03,04,05,06,07,08,16,17,18,19,20,21,22,23
                           label:
           notify_success_script:
              notify_success_arg:
    notify_success_warnings_only: 0
     notify_success_changes_only: 0
           notify_failure_script:
              notify_failure_arg:
                  restore_client:
                     dedup_group: global
               client_can_delete: 1
                 client_can_diff: 1
         client_can_force_backup: 1
                 client_can_list: 1
              client_can_restore: 1
               client_can_verify: 1
              server_can_restore: 1
                      breakpoint: 0
```

--------------------------------------

For me, normally my configuration seems correct?
but here is the result after a backup

--------
/var/spool/burp/poste999/current/incexc
--------
```
include = C:/Users/Utilisateur/Desktop/Drive_E
nobackup = .nobackup
exclude_regex = ^[A-Z]:/\$recycle\.bin$
exclude_regex = ^[A-Z]:/hiberfil\.sys$
exclude_regex = ^[A-Z]:/pagefile\.sys$
exclude_regex = ^[A-Z]:/recycler$
exclude_regex = ^[A-Z]:/swapfile\.sys$
cross_all_filesystems = 0
read_all_fifos = 0
read_all_blockdevs = 0
min_file_size = 0
max_file_size = 0
split_vss = 0
strip_vss = 0
acl = 1
xattr = 1
atime = 0
scan_problem_raises_error = 0
overwrite = 0
strip = 0

compression = 9
```

--------
--------
It seems that he is completely mocking the server side configuration.
However with the command "burp -c /etc/burp/burp-server.conf -t -C poste999" it seems nevertheless correct.

- No consideration regex
- No consideration VSS

Regards,
